In [1]:
#自己試玩
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
print(f"this is a={a}")

a[:,2] # returns the third columm


this is a=[[1 2 3 4]
 [5 6 7 8]]


array([3, 7])

In [2]:
set1:set={3,1,4,5,9,1} #set 不能重複，最後一個1 會自動略過
set1.add(6) #增加元素不會在最後，Set自動排序

set1

{1, 3, 4, 5, 6, 9}

In [3]:
import numpy as np
import random
array1:np.ndarray=np.array(range(1,100,11))

#print(random.randint(1,100))
#array2:ndarray=np.array(random.random(1,100))


print(f"目前的array1={array1}")
array1=array1+10
print(f"array1+10={array1}")


目前的array1=[ 1 12 23 34 45 56 67 78 89]
array1+10=[11 22 33 44 55 66 77 88 99]


In [4]:
display(np.arange(1.3,3.5,0.1))
display(np.linspace(1,20,20))

array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [5]:
display(np.random.random())
display(np.random.randn(10)) #常態分佈

0.6353706700391323

array([-1.38675669,  2.33197762, -0.55938954, -0.39317002,  0.04257645,
        1.27815393, -0.59357294,  0.50241745, -0.15667249,  0.46980822])

In [6]:
np.random.randint([1, 5, 7], 10)
display(np.random.random())
display(np.random.randn(10,5,3))
display(np.random.randint(1,10,size=(10,5)))

0.5142661870085902

array([[[ 6.29820129e-01,  1.77376332e+00,  6.12448375e-01],
        [-6.03589385e-01,  2.99072830e-01,  1.84604137e+00],
        [ 1.87428499e-01, -2.13665987e-01, -2.54555215e-01],
        [ 7.55830498e-01,  1.95126168e-02,  3.44391005e-01],
        [ 1.05777804e+00,  1.42195979e-01,  2.69158923e-02]],

       [[ 1.08201672e+00, -1.56676291e-03,  5.33330157e-01],
        [-3.52806426e-02, -1.02985410e+00,  2.97156762e-03],
        [ 7.30115946e-01, -9.41013839e-01, -3.08241356e-01],
        [-6.29892118e-01, -1.93472416e+00, -1.06314291e+00],
        [ 2.59674809e-01,  2.00510618e-03,  2.92600518e-01]],

       [[-2.46608025e+00,  4.55029267e-02,  1.00955631e+00],
        [-9.94826526e-03, -5.91777818e-01, -8.47079291e-01],
        [-1.02012752e+00, -6.48060978e-01,  1.20897007e+00],
        [ 3.17306507e-01,  2.01469185e+00, -6.71491965e-01],
        [ 8.32464592e-01, -5.66875294e-01,  5.59438816e-01]],

       [[-1.92944744e-01,  7.02165928e-01, -4.99511277e-01],
        [-2.609425

array([[8, 5, 3, 6, 9],
       [1, 8, 5, 9, 8],
       [6, 5, 3, 4, 7],
       [7, 8, 1, 5, 8],
       [2, 4, 1, 3, 9],
       [2, 8, 8, 4, 8],
       [7, 1, 4, 1, 3],
       [9, 2, 5, 8, 7],
       [9, 1, 7, 4, 7],
       [7, 9, 2, 7, 4]])